### ISSUE TITLE
Add a "follow all" button to the index page

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#100]
Following a case is a fundamental feature of EBWiki building user engagement with these cases. So we want to make it easy for users to follow as many cases as possible. Here is one way to do that.

User should be able to follow all articles on the root page or @articles returned from a keyword or search by state query.  User would click "follow all" from the index view. This would work on search results as well to follow a subset of @articles. We also need an "unfollow all button". I think prior to adding this button, we should implement blurbs to provide more informative updates.

A future enhancement would allow users to automatically follow any future cases that fit their searched for criteria, s.t. if a user searched for and followed all cases in NY, they would automaticaly follow any new cases added from NY.

Another improvement wouls add a Twitter-style checkbox to the index view s.t. a user could click to follow an individual case without going all the way to the article/show view.  Not sure if this would be a common use case, since presumably a user will either want to know some facts about a case b4 following it in which case, they have to visit the show page, or they want to follow all cases, or all cases in  CA etc which they will be able to do with a "follow all" button.

**Comment by trystant** [comment]
I think that this feature needs some thought attached to it before pushing it out to the world at large. Let's say that someone decided they want to follow a group of cases. Would it be for all cases in an area? Would it be for all cases as a result of a search? How would the UI be different for following multiple cases as opposed to following one case?

**Comment by campgurus** [comment]
Agree on doing some more thinking in this.

**Comment by campgurus** [comment]
Still thinking about this. I think the cases available for following from the index page should reflect @articles. So if a user has entered search terms "taser", they can follow every case that mentions taser. If a user enters a state, like NY, they can the click to follow all cases in NY. or any combination of criteria that results in an @articles.count > 0

**Comment by rlgreen91** [comment]
Hmm, so I think that it is a good idea to allow users to follow all cases that fit a certain criteria.  What I'm imagining here is that on a search results page, there is some type of UI element that allows the user to select to follow cases under that criteria.  What this means is that not only do we need to make that user follow those cases, but that we also need a way to track new and recently updated cases, evaluate them based on the user's criteria, automatically add the user as a follower if applicable, and then notify the user (preferably with an email digest if there are multiple cases over a period of time).  That also means that we would need a way to unfollow search criteria, although I don't know that we would necessarily want them to automatically unfollow cases.

I don't see a particular reason to list this on the index page. Those are just random cases - don't we want people to follow the cases that matter to them?

Can you explain what you mean by the blurb?

I think we can use the checkbox on the search results page, since a user may not want to follow that criteria but want to follow one or more cases.  But yeah, this will take a bit more thought.  I think the first question we have to ask is how do we separate following one or more cases from following cases that fall under a set of criteria.

**Comment by campgurus** [comment]
I believe "blurb" referenced the summary of change field that the editor must include to edit an article, that now populate the history tab. When the issue was created, I don't think we had implemented that feature.

agree this is not appropriate on the index page, but only on search results page. or maybe on the show page for a user to follow all "nearby" cases listed at the bottom of the page.

**Comment by rlgreen91** [comment]
Since we all agreed this didn't really make sense as written, I'm going to close this issue.
