### ISSUE TITLE
Update Mission Statement

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1115]
On the about page, replace the two mission statement sections with a single statement, printed below, under the heading "Our Mission"

EBWiki is singularly devoted to  providing the public with the tools needed to end police brutality and indiscriminant killing by police of African-Americans and other people of color through reliable information and resources. EBWiki's crowdsourced information platform allows families and community organizations to review the progression of current and past cases in real time.  Users can easily share information across numerous geographies.

While we recognize the need for quality policing, and the need for officers to defend themselves, reviewing the police killings such as Michael Brown, Trayvon Martin and the innumerable amount of less publicized cases, it is clear that this country has a troubling relationship between law enforcement and citizens of color.

In the most egregious of these cases where there is irrefutable, public documentation of police abuses in the form of video or audio recordings, we have often seen protests, violence and a spate of news stories. However, usually within a few weeks of the incident, public interest fatigues and the story fades from public discourse. At EBWiki, we believe strongly, after decades of observing this pattern, that it will not correct itself. EBWiki is here to help extend our collective attention span, creating more active awareness that will positively affect each case.

For example, there was a case involving the shooting of two unarmed homeless people by Cleveland Police Officer Scott Brelo. In that case, after a car chase of the two victims, Officer Brelo stood on the hood of their parked car and emptied 15 rounds through their windshield riddling both of their bodies with bullets, ensuring their death. Yet despite being indicted, Officer Brelo was found innocent two years later in a directed verdict announced quietly on a holiday weekend. We believe that EBWiki’s researchers shining a light on these legal proceedings as they are happening will lead to the level of public involvment that will lead to more equitable results.

In addition to its primary focus, EBWiki takes a slightly different approach in tracking these cases by regularly tracking community organization responses, litigation procedures, and continuously gathering relevant facts that help us learn the full scope of each circumstance. Questions such as, “Was there an indictment or conviction?”, “Where is the officer in question working now?” and “What related indignities have whistleblowers endured?” are just a few of the aspects we report on.

Likewise, by tracking the activity of community groups and families in these cases as they occur across America, we believe we can facilitate sharing of key information that will allow these groups and families to learn from each other’s experiences and improve their collective responses to these events when they occur.

Perhaps most importantly and succinctly stated, our ultimate goal is to extend the lives of subjects beyond the two-week attention span of the mainstream media to enable us to organize a collective response politically or otherwise.

This is related to Issue #492

**Comment by campgurus** [comment]
I want to revisit this issue before adopting this change.  I think many of the changes to wording are appropriate.  I also think labeling these two separate sections as EBWiki's Mission and Our Mission (basically the same label), is a mistake that needs to be fixed. However, I think the organization of the page is actually correct.

In general, I think having shorter sections with headings is more engaging than having one longer section so I would hesitate to lengthen any one section.

As to the overall organization of the page, currently the first section speaks about the problem and our overall goal. It is correctly labeled "our mission." In the second section, we talk specifically about the first step in addressing the problem we identified in the first section, and applaud the work others are doing with respect to inventorying these cases.  The last section is incorrectly labeled.  The goal of that third section, after identifying the problem and talking about what others are doing, is to talk specifically about building on the work others are doing and to highlight the unique additions EBWiki hopes to bring to this arena which are:

- our focus on cases involving people of color
- the ability to focus attention on the progress of these cases over time
- ability to easily share info and best practices for combatting analogous behaviors  in various locales
- ability to organize and publicize specific events and actions

So, instead of combining the Mission sections, I think we relabel the last section more appropriately and apply the wording changes in the text above.

**Comment by rlgreen91** [comment]
That makes sense to me.

**Comment by rlgreen91** [comment]
Merged as part of #1292
