### ISSUE TITLE
Redirect newly registered users to previous action 

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1240]
We have certain actions which require a user to be logged in to execute. eg to create, edit, fllow or comment on a case, a user must be logged in.

When an unregistered user attempts one of these actions, they are redirected to the sign-up page. Devise provides functionality to get the user back to the original impetus for their registration.

Here is a link that will be helpful to implement this: https://github.com/plataformatec/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update.

This may also be a place where modal forms would solve the problem as well, since when the sign-up is complete, the modal closes, leaving the user back on the original page.

**Comment by rlgreen91** [comment]
This functionality should be enabled for any time a user is not logged in, regardless of whether they need to sign up or login.

I do not recommend using a modal, because multiple features of the page may need to be re-rendered to account for the user being logged in.

One thing to consider is that we have on-boarding for new users, suggesting that they follow cases and stuff.  We'll want to provide some way to still have users go through that page or series of tasks even as we allow them to go back to what they were doing.

**Comment by campgurus** [comment]
Can you give an example of what this means outside the context of a newly logged in user?

Trying to understand what you mean by:

> This functionality should be enabled for any time a user is not logged in, regardless of whether they need to sign up or login.

**Comment by rlgreen91** [comment]
I mean that, if I try to leave a comment, but I'm not logged in, I should get sent to a page allowing me to either sign up or log in.  Once I log in, I should be redirected back to the page where I wanted to leave my comment.

**Comment by rlgreen91** [comment]
There are a bunch of new issues focused specifically on adding this functionality in the controllers.  As such, this can be closed.
