### ISSUE TITLE
Links out of order

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1928]
We had been listing external links at the bottom of the case pages in revers chron order. It now seems that has gone awry. screenshot below:

<img width="682" alt="screen shot 2018-07-31 at 7 51 48 am" src="https://user-images.githubusercontent.com/1260659/43458094-ef8d2c3c-9496-11e8-92cc-12eff3108a8b.png">

**Comment by rlgreen91** [comment]
Completing this issue requires two things:

- Rather than looping through the list of links using `each`, create a partial to contain the HTML and pass the collection of links to that.  You can look at how we handle the thumbnails for the case index view as an example.

- In the link, we still want to keep the `_blank` target to open the link in another tab, but we should add `rel="noopener noreferrer"` for security purposes.  There's probably a Stack Overflow answer on how to do that within `link_to` somewhere.

**Comment by carloslazo** [comment]
I can take this on. Can't seem to find a way to self assign though?

**Comment by carloslazo** [comment]
I created a PR with the changes you mentioned. 

One thing that I want to know is how creating a collection of links will fix the links out of order issue? Or was I blindly just following directions without addressing the issue?

Let me know. Thanks.

**Comment by carloslazo** [comment]
Double checked and it seems that I still haven't fixed the issue.

**Comment by rlgreen91** [comment]
Addressed in #3240
