### ISSUE TITLE
Install Microsoft Webmaster Tool authentication

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#250]
The goal is to reduce the number of requests coming from Bingbot like this one: 
<img width="1280" alt="screenshot 2015-10-06 04 20 48" src="https://cloud.githubusercontent.com/assets/13509/10303427/a7bc6606-6be1-11e5-9d04-7ee7bee91966.png">

**Comment by campgurus** [comment]
I think the problem is that the /follows route gets hit whenver a user clicks the follow button. So I think the search engine bots are recording those urls as pages and trying to ping them.  See the urls fromt he crawl errors listed in Google Webmaster.  I am not sure how to exclude all /follows urls from Google/Bing.

<img width="1013" alt="screen shot 2016-02-29 at 5 46 00 am" src="https://cloud.githubusercontent.com/assets/1260659/13392351/d9d0d864-dea7-11e5-8260-2bb59818b09e.png">

**Comment by trystant** [comment]
This also doesn't deal with the work of setting up Bing Webmaster Tools

**Comment by trystant** [comment]
I think that a solution would be to disable the default action in
JavaScript so that when the button is clicked, the link is not actually
requested.

**Comment by campgurus** [comment]
I don't know how to do that.

**Comment by trystant** [comment]
A Google search "install Bing Webmaster Tools on an account"
>
>
led to this page. Seems like a good place to start, whoever ends up doing
this.

https://www.bing.com/webmaster/help/getting-started-checklist-66a806de

**Comment by trystant** [comment]
Since we've removed the RoutingErrors that occur in Rollbar, I believe that we can close this.
