### ISSUE TITLE
Implement Tests Using GitHub Actions

### ISSUE THREAD

**Issue by managedkaos** [EBWiki/EBWiki#3709]
Travis builds are failing for various reasons.

Replicate and/or improve the Travis workflow in a GitHub Actions workflow.

**Comment by managedkaos** [comment]
Close to being closed by #3781.
There is still a Travis run getting picked up from somewhere.

**Comment by managedkaos** [comment]
GitHub Actions workflow has been implemented (or at least kicked off decently) and recent PRs have fixed issues.

**Comment by mockdeep** [comment]
@managedkaos @trystant @rlgreen91 I'm curious how you all feel about using CircleCI instead of Github Actions. I've been using Github Actions on some projects and CircleCI on others, and I'm still finding CircleCI to be the better option. Benefits:

* Builds seem to be consistently faster and more reliable. I've had a number of situations where the build hangs after 10 minutes on Github Actions. I've even seen a couple build hangs on my PRs on EBWiki.
* CircleCI has a nicer UI. It's pretty awkward to get to the actual failure on Github Actions. CircleCI focuses the failure and gives you a nice description if you use their test reporter.
* All steps run on CircleCI. On Github Actions it kills ongoing build steps when one step fails. This is often frustrating when you're trying to get a better picture of exactly which tests are failing and why.
* Parallelization. CircleCI has some great parallelization tools. The build runs pretty fast right now, but on CircleCI you can easily split builds up into as many as 80 separate jobs.

If you're game, I'm pretty familiar with CircleCI and can set it up for EBWiki.
