### ISSUE TITLE
Update "About" page to reflect the position of EBWiki

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#492]
One thing which may not be readily apparent is that EBWiki supports justice for people. Dylan Rooff shot 9 people in a church and was not killed, but received due process. EBWiki does not claim innocence or guilt for any of the people involved in these interactions with law enforcement; just that people who have not been violating the law have a right to not be killed.

For example, if someone opened fire on police officers while they were doing their duty, the officers have a right to defend themselves and someone killed as a result of that wouldn't be listed on this page.

**Comment by trystant** [comment]
Here's some copy for the About page:

# Disclaimer
EBWiki.org does not take a position on the innocence or guilt of the parties who died in these interactions with law enforcement. We do not think it's central to the idea of justice for all without bias. For example, Dylan Roof shot 9 people in a church, was calmly arrested and received food from [Burger King](http://www.snopes.com/2015/06/22/dylann-roof-burger-king/). Every person on this site deserves similar treatment.

@campgurus, what are your thoughts?

**Comment by campgurus** [comment]
not sure this is better, but here is a shot.  it is longer which I didn't want, but let's iterate.

EBWiki.org does not consider the innocence or guilt of the people whose cases we present on this site. Some of their stories will be extremely sympathetic. Others will be less so. In our opinion, when it comes to the promise of equal treatment by law enforcement, guilt or innocence is largely irrelevant. In our legal system, the determination of guilt comes not on street corners from police, but is meted out in courtrooms by judges and juries. 

We contrast the case of Dylan Roof who shot 9 people while they worshipped in a church, yet was calmly arrested, provided food, and escorted to jail with that of Tamir Rice who was shot in a playground within seconds of police arrival. Our goal at EBWiki is simply to ensure equally humane treatment by police of all people.

**Comment by campgurus** [comment]
Thinking about this a bit more.  I think maybe the solution for this and other questions that arise in the future is to add a set of faq at the button of the about page to address these issues without requiring us to change the meat of the about page every time.

**Comment by campgurus** [comment]
Revisiting this, I think my reformulation may be off. I think we should consider the question of whether EBWiki takes positions at all and on what. Our name is "EndBias", so it seems we take a clear position on systemic inconsistencies in the treatment of people by law enforcement esp POC. The About page reflects that position. 

On the other hand, in point of fact, we have taken pains to avoid EBWiki taking explicit positions on specific cases within the body of cases. I am not sure whether we think this is an inconsistency necessitating a changed approach or not.

**Comment by trystant** [comment]
I don't think so. I think that a "just the facts of the case" interpretation, without taking a position, is the stance we want to have. The only question is whether there's something worth adding to the "About" page that would clarify the situation.

**Comment by rlgreen91** [comment]
I think it is worth having something added to the About page for clarification.  How about something like this?

The End Bias Wiki (EBWiki) is a crowd-sourced encyclopedia that aims to reduce the amount of racial biases in police-civilian interactions by raising awareness of the many people of color who are killed as a result of police-civilian interactions rather than charged, arrested, and tried for one or more crimes.  However, some of these cases are not necessarily clear-cut. In some cases, it may be easy to point to an innocent victim, while in others it may be difficult to find sympathy for the deceased based on their actions prior to the shooting.

At its core, EBWiki is committed to justice for all citizens, from innocent civilians who are not committing a crime, to criminals who have the right to be tried by a jury of their peers, to police officers who are upholding their duty to protect and serve their communities.  To uphold this commitment, EBWiki lists the facts of each case fitting within our criteria - EBWiki does not consider the innocence or guilt of any of the actors involved in the case, and does not take an official position on any of the cases.  Instead, EBWiki is committed to educating others about the factual nature of these cases, in the hopes that as a result of this education, law enforcement, government, and communities may work together to reduce the amount of racial biases in police-civilian interactions in the future.

**Comment by rlgreen91** [comment]
Did we ever come to a decision about this?  Can we decide on this by the end of the week and update the page?

**Comment by rlgreen91** [comment]
I know this is assigned to you @trystant, but since I only kinda heard back from everyone, I'm just going to go with what I put above, with some minor edits, since I remember there being consensus regarding it.  I'll go ahead and update the page now.

**Comment by campgurus** [comment]
I think the language above looks good. What are you thinking in terms of separating the pages?  Should we make a google doc with the proposed language that can accommodate us working on the same document and commenting on specific sections?

**Comment by rlgreen91** [comment]
So, I actually had Annie create a version of the combined mission section - I'll post that in Slack so you can review it.  As for separating the pages, what I'm thinking is that we'll have an About section of the website, containing each of these subsections as pages. When it comes to the content of specific pages, let's lean on Annie as much as we can.

**Comment by rlgreen91** [comment]
I think that as of now, we can close this.  This page has since been updated with the new copy, and we'll be making slight changes in the future as we redo the organization of the landing page and that affects links it contains.
