### ISSUE TITLE
Change page loading from from pagination to "infinite scroll" or "load more" button

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#576]
We currently use pagination to manage the loading of resources on the index page.  We only load new images when the user clicks on a new page. We could achieve the same benefits of on-demand resource loading more elegantly with an endless scroll wherein new images and links are loaded on demand as the user scrolls down the page or with the use of a load more button combined with lazy loading. 

I think either new method would also result in more users seeing more cases with less effort. Infinite scroll leads to the most browsing, but "load more" buttons have the benefit of not obscuring the page footer to the extent we think those links are important.  In our case, I don't believe we are getting any clicks on footer links.  And the are also present on other pages where the inffinite scroll would not be present.

here is an interesting analysis of the alternatives: https://www.smashingmagazine.com/2016/03/pagination-infinite-scrolling-load-more-buttons/

and an alternative view arguing in favor of pagination:
http://www.creativebloq.com/ux/paginate-or-infinite-scroll-71515816

here is a gem that enables infinite scrolling in rails working with the kaminari gem we are using: https://github.com/magoosh/jquery-infinite-pages

here is an tutorial that uses javascript without disrupting the traditional pagination: https://www.youtube.com/watch?v=PQX2fgB6y10

This is something we might be able to test with split, if we could decide on an appropriate "success" metric.

**Comment by rlgreen91** [comment]
I personally prefer pagination over infinite scrolling, primarily because infinite scroll takes away your sense of place should you need to navigate somewhere else within the site.  It's almost impossible for you to navigate back to where you were.

I think there are separate issues here that we should examine, namely "what use do we get out of the footer" and enabling lazy loading of images where possible.  We could even look into switching from kaminari to pagy as our pagination gem.  But those are separate issues.

What do you think @campgurus @trystant ?

**Comment by mnyon-grandkru** [comment]
I think I'm okay with pagination here. There's also the potential mental cost of endlessly scrolling. I think we can close this ticket for now as well.  If we want to re-open after the upgrade, we can.
