### ISSUE TITLE
Update emails to followers delayed and duplicated

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#740]
I have experienced the following issues several times recently:
- emails to followers are sent weeks after a case is updated - screenshots below:
  <img width="820" alt="screen shot 2016-07-26 at 1 21 58 pm" src="https://cloud.githubusercontent.com/assets/1260659/17148278/7d677fae-5334-11e6-9669-0234bf6f50f6.png">

but the history tab shows that this update happened weeks ago:
<img width="662" alt="screen shot 2016-07-26 at 1 22 17 pm" src="https://cloud.githubusercontent.com/assets/1260659/17148306/9ee5f386-5334-11e6-89ac-95c2861f553d.png">
- updates are re-forwarded to the same recipient within a few minutes. - screenshot below:

<img width="834" alt="screen shot 2016-07-26 at 1 16 45 pm" src="https://cloud.githubusercontent.com/assets/1260659/17148151/dd983efa-5333-11e6-9077-d21273dc6bfd.png">

**Comment by trystant** [comment]
@campgurus, have you had an instance of this recently? I've added a logging statement so that we have a baseline on when the emails were sent out from the mailers directly to compare against when they arrive in the box. 

After this, the next thing to do (IMO) is to hold and wait until the next occurrence and then use that logging info to figure out the discrepancy when it pops up.

Separately, the send_followers_email needs specs to cover them. One challenge that exists is that the mock_models used for the specs don't include every piece of data that the template could use. A solution to this is to replace the mock_models with an `author_with_case` factory (in `spec/factories/articles.rb`) and a `follower` factory ( in `spec/factories/user.rb`).  Once those are in place, specs for `UserNotifier.send_followers_email` can be written easily.

**Comment by campgurus** [comment]
I haven't noticed it recently, but I did not have an eye out. I will look for it going forward

**Comment by rlgreen91** [comment]
I am going to assume that this was a temporary issue with Sendgrid, given that no comments have been left in the past year.  In that case, this issue is now closed.
