### ISSUE TITLE
Refactor Index method for Articles Controller

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#855]
Refactor the index method in app/controllers/articles.rb.  Right now it uses guards to determine what cases to display, which is fine, but the code itself is not readable.  Update the code for style - break the functions into multiple lines if necessary.  Alternately, consider using some other type of conditional, like a case statement, if that will yield greater readability.

**Comment by trystant** [comment]
I don't think that this is a `quick fix`, due to the fact that the solution for this problem involves separating the filtering part into a separate concern. I plan on using [this](http://www.justinweiss.com/articles/search-and-filter-rails-models-without-bloating-your-controller/) blog post as a guide.

**Comment by rlgreen91** [comment]
As noted in the above comment, use the linked blog post as a guide to refactor the index method.

**Comment by rlgreen91** [comment]
This was actually completed as part of the `make_search_great_again` branch, so I'll close it.
