### ISSUE TITLE
Editor can remove all subjects on an article

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#87]
While using the admin, I accidentally removed all the subjects on the Michael Brown article. 

There was an error upon removing the last subject from the edit form:

```
 1431 2015-08-09T21:46:06.002014+00:00 app[web.1]: ActionView::Template::Error (undefined method `name' for nil:NilClass):
   1432 2015-08-09T21:46:06.002017+00:00 app[web.1]:     44:
   1433 2015-08-09T21:46:06.002027+00:00 app[web.1]:     48:           <small><%= @article.city %>, <%= @article.state.name %>. <%= @article.date.strftime("%B %d, %Y") %></small>
   1434 2015-08-09T21:46:06.002016+00:00 app[web.1]:     43:     </div>
   1435 2015-08-09T21:46:06.002023+00:00 app[web.1]:     46:       <h1 class="page-header articleTitle"><%= @subjects.first.name %>, <%= @subjects.first.age ? "#{@subjects.first.ag
   1436 2015-08-09T21:46:06.002025+00:00 app[web.1]:     47:       <br>
   1437 2015-08-09T21:46:06.002031+00:00 app[web.1]:
   1438 2015-08-09T21:46:06.002028+00:00 app[web.1]:     49:       </h1>
   1439 2015-08-09T21:46:06.002029+00:00 app[web.1]:   app/views/articles/show.html.erb:46:in `_app_views_articles_show_html_erb___3015967194760607353_70066027856860'
```

I've patched this by manually recreating a subject in the console, but we need to be sure that a user cannot remove all the subjects.

Here's the [rollbar](https://rollbar.com/trystant/BOW/items/131/) error involved.

**Comment by trystant** [comment]
@campgurus just giving you a heads up.

**Comment by campgurus** [comment]
ok.  we need to add validation to make sure that an article has at least one subject.  Adding validation is easy. I just was not able to get the rspec to work.  Once i added the validation many tests were failing as the factory was not adding a subject when creating articles.  this may have been fixed with the new transient approach you added a while back.  I will check and include a stack trace if it is still giving the same error as before.

**Comment by rlgreen91** [comment]
This looks done, as far as I can tell.
