### ISSUE TITLE
Refactor test cases in article spec

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#882]
In `article_spec.rb`, refactor the first set of test cases to fall under a `describe "versioning"` block when testing that the version number updates correctly.

**Comment by caseyprovost** [comment]
@rlgreen91 First off nice Friends name reference!

What kind of refactor are you looking for here? The tests themselves are pretty clean albeit quite explicit. We could use meta-programming to iterate through a list of properties to check versioning based on attribute change, but that would also be a little black magic.

Most of these tests just test that Papertrail works properly, and since Papertrail has it's own tests I think the better win here might me to remove all the versioning based unless you want to keep 1-2 around for regression sake.

**Comment by rlgreen91** [comment]
Hi @caseyprovost, I would like for the tests to be inside of a `describe "versioning` block, as I said above.  I do agree that a lot of these tests are really verifying that Papertrail works, but given that we are making other changes to the `article` model, I would like to keep them around for now just as a sanity check.

Please let me know if you have any other questions!

**Comment by rlgreen91** [comment]
This was fixed a while back, it seems, just never closed.
